theme: minima
title: Livros Livres
author: GitHub User
email: oi@lauradavina.com
description: > # this means to ignore newlines until "baseurl:"
  Experimentação com livros livres. 
  Livre de matéria, de tinta, cola e costura
# social links
instagram_username: lauradavina # DO NOT include the @ character, or else the build will fail!
github_username:  lauradavina # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
